### ISSUE TITLE
PHP Check

### ISSUE THREAD

**Issue by matthewhirsch** [DaanDD/material-syntax#1]
This is great mate!

Just a quick thing, can you double check the formatting of basic PHP tags? Color seems off in relation to the rest of the colors but maybe it's just me. Everything else looks great so far!

**Comment by DaanDD** [comment]
Thanks for the report! The coloring was indeed a bit off in some places, it should be better now. Let me know how you like it and if you spot any more errors.

**Comment by matthewhirsch** [comment]
love it!
