### ISSUE TITLE
Deprecated selector in `material-syntax/index.less`

### ISSUE THREAD

**Issue by vjandrea** [DaanDD/material-syntax#5]
In `material-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,
:host .gutter .line-number:after,
atom-text-editor .fold-marker:after,
:host .fold-marker:after` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after,
atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `atom-text-editor .invisible,
:host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `.comment` => `.syntax--comment`

* `.entity.name.type` => `.syntax--entity.syntax--name.syntax--type`

* `.entity.other.inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class`

* `.keyword` => `.syntax--keyword`

* `.keyword.control` => `.syntax--keyword.syntax--control`

* `.keyword.control.php` => `.syntax--keyword.syntax--control.syntax--php`

* `.keyword.control.at-rule` => `.syntax--keyword.syntax--control.syntax--at-rule`

* `.keyword.control.at-rule .keyword` => `.syntax--keyword.syntax--control.syntax--at-rule .syntax--keyword`

* `.keyword.operator` => `.syntax--keyword.syntax--operator`

* `.keyword.other.special-method` => `.syntax--keyword.syntax--other.syntax--special-method`

* `.keyword.other.unit` => `.syntax--keyword.syntax--other.syntax--unit`

* `.storage` => `.syntax--storage`

* `.storage.modifier.php` => `.syntax--storage.syntax--modifier.syntax--php`

* `.constant` => `.syntax--constant`

* `.constant.character.escape` => `.syntax--constant.syntax--character.syntax--escape`

* `.constant.numeric` => `.syntax--constant.syntax--numeric`

* `.constant.other.color` => `.syntax--constant.syntax--other.syntax--color`

* `.constant.other.symbol` => `.syntax--constant.syntax--other.syntax--symbol`

* `.type` => `.syntax--type`

* `.type.property-name` => `.syntax--type.syntax--property-name`

* `.variable` => `.syntax--variable`

* `.variable.other` => `.syntax--variable.syntax--other`

* `.variable.other.less` => `.syntax--variable.syntax--other.syntax--less`

* `.variable.parameter.function` => `.syntax--variable.syntax--parameter.syntax--function`

* `.invalid.illegal` => `.syntax--invalid.syntax--illegal`

* `.string` => `.syntax--string`

* `.string.regexp` => `.syntax--string.syntax--regexp`

* `.string.regexp .source.ruby.embedded` => `.syntax--string.syntax--regexp .syntax--source.syntax--ruby.syntax--embedded`

* `.string.other.link` => `.syntax--string.syntax--other.syntax--link`

* `.punctuation.definition.comment` => `.syntax--punctuation.syntax--definition.syntax--comment`

* `.punctuation.definition.begin,
.punctuation.definition.end` => `.syntax--punctuation.syntax--definition.syntax--begin,
.syntax--punctuation.syntax--definition.syntax--end`

* `.punctuation.definition.string,
.punctuation.definition.variable,
.punctuation.definition.parameters,
.punctuation.definition.array` => `.syntax--punctuation.syntax--definition.syntax--string,
.syntax--punctuation.syntax--definition.syntax--variable,
.syntax--punctuation.syntax--definition.syntax--parameters,
.syntax--punctuation.syntax--definition.syntax--array`

* `.punctuation.definition.heading,
.punctuation.definition.identity` => `.syntax--punctuation.syntax--definition.syntax--heading,
.syntax--punctuation.syntax--definition.syntax--identity`

* `.punctuation.definition.bold` => `.syntax--punctuation.syntax--definition.syntax--bold`

* `.punctuation.definition.italic` => `.syntax--punctuation.syntax--definition.syntax--italic`

* `.punctuation.section.embedded` => `.syntax--punctuation.syntax--section.syntax--embedded`

* `.support.class` => `.syntax--support.syntax--class`

* `.support.function` => `.syntax--support.syntax--function`

* `.entity.name.function` => `.syntax--entity.syntax--name.syntax--function`

* `.entity.name.class,
.entity.name.type.class` => `.syntax--entity.syntax--name.syntax--class,
.syntax--entity.syntax--name.syntax--type.syntax--class`

* `.entity.name.section` => `.syntax--entity.syntax--name.syntax--section`

* `.entity.name.tag` => `.syntax--entity.syntax--name.syntax--tag`

* `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`

* `.entity.other.attribute-name.class` => `.syntax--entity.syntax--other.syntax--attribute-name.syntax--class`

* `.entity.other.attribute-name.id` => `.syntax--entity.syntax--other.syntax--attribute-name.syntax--id`

* `.meta.class` => `.syntax--meta.syntax--class`

* `.meta.link` => `.syntax--meta.syntax--link`

* `.meta.function-call,
.meta.require` => `.syntax--meta.syntax--function-call,
.syntax--meta.syntax--require`

* `.meta.selector` => `.syntax--meta.syntax--selector`

* `.meta.tag` => `.syntax--meta.syntax--tag`

* `.meta.separator` => `.syntax--meta.syntax--separator`

* `.none` => `.syntax--none`

* `.markup.bold` => `.syntax--markup.syntax--bold`

* `.markup.changed` => `.syntax--markup.syntax--changed`

* `.markup.deleted` => `.syntax--markup.syntax--deleted`

* `.markup.italic` => `.syntax--markup.syntax--italic`

* `.markup.heading .punctuation.definition.heading` => `.syntax--markup.syntax--heading .syntax--punctuation.syntax--definition.syntax--heading`

* `.markup.inserted` => `.syntax--markup.syntax--inserted`

* `.markup.list` => `.syntax--markup.syntax--list`

* `.markup.quote` => `.syntax--markup.syntax--quote`

* `.markup.raw.inline` => `.syntax--markup.syntax--raw.syntax--inline`

* `.source.gfm .markup` => `.syntax--source.syntax--gfm .syntax--markup`

* `.source.gfm .markup.heading` => `.syntax--source.syntax--gfm .syntax--markup.syntax--heading`

* `.source.gfm .markup.heading .marker` => `.syntax--source.syntax--gfm .syntax--markup.syntax--heading .syntax--marker`

* `atom-text-editor[mini] .scroll-view,
:host([mini]) .scroll-view` => `atom-text-editor[mini] .scroll-view,atom-text-editor .scroll-view`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by vjandrea** [comment]
I am preparing a pull request [here](https://github.com/vjandrea/material-syntax/tree/hotfix-5), but i'm not sure if what is suggested by Atom issue report makes sense:
````less
atom-text-editor .search-results .marker .region,
atom-text-editor .search-results .marker .region {
  background-color: transparent;
  border: 1px solid @syntax-result-marker-color;
}
````
Personally i would avoid the duplication, leaving simply
````less
atom-text-editor .search-results .marker .region {
  background-color: transparent;
  border: 1px solid @syntax-result-marker-color;
}
````

**Comment by vjandrea** [comment]
I still see two deprecations, looks like i missed .syntax--marker. I paste here the error message and investigate later.

`atom-text-editor .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region`
`atom-text-editor .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region`

**Comment by vjandrea** [comment]
Sorry @DaanDD , i opened a new PR with the missing selectors.

**Comment by lmj0011** [comment]
>Sorry @DaanDD , i opened a new PR with the missing selectors.

just confirming this warning is in the latest release
material-syntax@0.6.0

**Comment by vjandrea** [comment]
@lmj0011 can you please confirm that you see only two deprecations?

**Comment by lmj0011** [comment]
@vjandrea 
![warning](https://cloud.githubusercontent.com/assets/9396189/22498278/ed580d10-e81c-11e6-99dd-8e2c202386be.png)

for material-syntax@0.6.0

**Comment by vjandrea** [comment]
Thanks @lmj0011, my latest PR #7 fixes those selectors too. Now let's wait for @DaanDD to merge it.

**Comment by vjandrea** [comment]
Deprecations gone, now this issue is definitely closed :-)
